### ISSUE TITLE
Data Truncation error with Towny accounts

### ISSUE THREAD

**Issue by Kwikxilver** [Avankziar/AdvanceEconomyPlus#1]
Hey mate. Love the plugin, I'm having an issue using it with Towny though. When new accounts try to be created for towns that have long names, it just doesn't connect correctly due to the length. Looks like a mysql error. Any help fixing the error below?

Cheers!

```
01.08 23:11:05 [Server] WARN [AdvanceEconomyPlus] Error: Data truncation: Data too long for column 'player_name' at row 1
01.08 23:11:05 [Server] WARN com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'player_name' at row 1
01.08 23:11:05 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
01.08 23:11:05 [Server] WARN at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
01.08 23:11:05 [Server] WARN at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
01.08 23:11:05 [Server] WARN at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
01.08 23:11:05 [Server] WARN at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
01.08 23:11:05 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
01.08 23:11:05 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136)
01.08 23:11:05 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2070)
01.08 23:11:05 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5187)
01.08 23:11:05 [Server] WARN at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2055)
01.08 23:11:05 [Server] WARN at main.java.me.avankziar.advanceeconomy.spigot.database.tables.TableI.createI(TableI.java:92)
01.08 23:11:05 [Server] WARN at main.java.me.avankziar.advanceeconomy.spigot.database.MysqlHandler.create(MysqlHandler.java:76)
01.08 23:11:05 [Server] WARN at main.java.me.avankziar.advanceeconomy.spigot.api.VaultApi.createPlayerAccount(VaultApi.java:450)
01.08 23:11:05 [Server] WARN at main.java.me.avankziar.advanceeconomy.spigot.api.VaultApi.createPlayerAccount(VaultApi.java:460)
01.08 23:11:05 [Server] WARN at com.palmergames.bukkit.towny.TownyEconomyHandler.getBalance(TownyEconomyHandler.java:258)
01.08 23:11:05 [Server] WARN at com.palmergames.bukkit.towny.object.EconomyAccount.getHoldingBalance(EconomyAccount.java:174)
01.08 23:11:05 [Server] WARN at com.palmergames.bukkit.towny.object.EconomyAccount.getHoldingFormattedBalance(EconomyAccount.java:199)
01.08 23:11:05 [Server] WARN at com.palmergames.bukkit.towny.TownyFormatter.getStatus(TownyFormatter.java:391)
01.08 23:11:05 [Server] WARN at com.palmergames.bukkit.towny.command.TownCommand.lambda$13(TownCommand.java:856)
01.08 23:11:05 [Server] WARN at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
01.08 23:11:05 [Server] WARN at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
01.08 23:11:05 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
01.08 23:11:05 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
01.08 23:11:05 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
01.08 23:11:05 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

**Comment by Avankziar** [comment]
I´m sorry, I oversee this issue. And yes, this is a mysql problem.
I make a bigger colume for the future. You can make than in mysqladmin too. Simply make the number bigger^^

Edit: But is this really a good idea to create player accounts for a city at Towney?
Would I rather do it with the future banks then...

**Comment by Avankziar** [comment]
It is a while, but I have make Banks possible!
=> https://github.com/Avankziar/AdvanceEconomyPlus/wiki/GER-Home#accounts
=> https://github.com/Avankziar/InterfaceHub/wiki/GER-Explanation-for-Economy
